# Generated by Django 3.2.11 on 2022-03-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jet_django', '0003_auto_20191007_2005'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
