# Generated by Django 3.0.5 on 2022-03-30 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('P_category_id', models.IntegerField(default='0')),
                ('sub_category', models.CharField(choices=[('Man', (('Man_Footwer', 'Footwer'), ('Man_T-shirt', 'T-shirt'), ('Man_Kurta', 'Kurta'), ('Man_Smart Watches', 'Smart Watches'), ('Man_Sports & Fitness Store', 'Sports & Fitness Store'))), ('Woman', (('Woman_Footwer', 'Footwer'), ('Woman_T-shirt', 'T-shirt'), ('Woman_Kurta', 'Kurta'), ('Woman_Smart Watches', 'Smart Watches'), ('Woman_Sports & Fitness Store', 'Sports & Fitness Store'))), ('KId', (('KId_Footwer', 'Footwer'), ('KId_T-shirt', 'T-shirt'), ('KId_Kurta', 'Kurta'), ('KId_Smart Watches', 'Smart Watches'), ('KId_Sports & Fitness Store', 'Sports & Fitness Store'))), ('Electronic', (('Electronic_Mobiles', 'Mobiles'), ('Electronic_Laptops', 'Laptops'), ('Electronic_Speakers', 'Speakers'), ('Electronic_Smart Home Automation', 'Home Automation'), ('Electronic_Network Components', 'Network Components'), ('Electronic_Health Care Appliances', 'Health Care Appliances')))], default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Surname', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Display_picture', models.ImageField(default='image', upload_to='images')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app4.Position')),
            ],
        ),
    ]
