# Generated by Django 4.0.3 on 2022-03-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JetApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Display_picture',
            field=models.ImageField(default='image', upload_to='images'),
        ),
    ]
